# Generated by Django 3.2.12 on 2024-12-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
